name: media_picker_example
description: Demonstrates how to use the media_picker plugin.

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  media_picker:
    path: ../


flutter:

  uses-material-design: true

