name: media_picker
description: Flutter plugin to get pictures and videos from the device. It allows you to select one or more images from gallery or camera, without needing to switch provider.
version: 1.2.3
author: Duarte Silveira <dsilveira@gmx.net>
homepage: https://github.com/d-silveira/flutter_media_picker

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.example.mediaspicker
    pluginClass: MediasPickerPlugin

environment:
  sdk: ">=1.19.0 <3.0.0"
